# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
  push:
  schedule:
    - cron: '0 22 * * *'
    - cron: '2 22 * * *'
    - cron: '4 22 * * *'
    - cron: '6 22 * * *'
      
      
    - cron: '0 4 * * *'
    - cron: '2 4 * * *'
    - cron: '4 4 * * *'
    - cron: '6 4 * * *'
      
    - cron: '0 10 * * *'
    - cron: '2 10 * * *'
    - cron: '4 10 * * *'
    - cron: '6 10 * * *'
      
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
    - name: Build and publish
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python e-report.py
